### PR TITLE
Pumps use FanEntity

### PR DESCRIPTION
**Pull request by los93sol**
Makes pumps come into Home Assistant as fans so variable speed pumps work as expected

### CODE REVIEW

**Comment by los93sol** [comment]
#8

**Comment by mikeboiko** [comment]
> #8

Thank you for implementing this feature. I was not able to get it to work successfully unfortunately.
I checked out the PR and I got the following error when I reloaded HA:
```
home-assistant     | 2021-06-03 13:56:48 ERROR (MainThread) [homeassistant.components.fan] Error adding entities for domain fan with platform gecko
home-assistant     | Traceback (most recent call last):
home-assistant     |   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
home-assistant     |     await asyncio.gather(*tasks)
home-assistant     |   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 499, in _async_add_entity
home-assistant     |     capabilities=entity.capability_attributes,
home-assistant     |   File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 512, in capability_attributes
home-assistant     |     attrs[ATTR_PRESET_MODES] = self.preset_modes
home-assistant     |   File "/config/custom_components/gecko/fan.py", line 51, in preset_modes
home-assistant     |     return self._automation_entity._user_demand["options"]
home-assistant     | AttributeError: 'GeckoPump' object has no attribute '_user_demand'
home-assistant     | 2021-06-03 13:56:48 ERROR (MainThread) [homeassistant.components.fan] Error while setting up gecko platform for fan
home-assistant     | Traceback (most recent call last):
home-assistant     |   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 258, in _async_setup_platform
home-assistant     |     await asyncio.gather(*pending)
home-assistant     |   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
home-assistant     |     await asyncio.gather(*tasks)
home-assistant     |   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 499, in _async_add_entity
home-assistant     |     capabilities=entity.capability_attributes,
home-assistant     |   File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 512, in capability_attributes
home-assistant     |     attrs[ATTR_PRESET_MODES] = self.preset_modes
home-assistant     |   File "/config/custom_components/gecko/fan.py", line 51, in preset_modes
home-assistant     |     return self._automation_entity._user_demand["options"]
home-assistant     | AttributeError: 'GeckoPump' object has no attribute '_user_demand'
```

**Comment by los93sol** [comment]
@mikeboiko  There's changes in geckolib as well that you need for it to work.  There's another PR on that repo as well

**Comment by mikeboiko** [comment]
> @mikeboiko There's changes in geckolib as well that you need for it to work. There's another PR on that repo as well

Oh gotcha. Does your repo have all the latest changes?
https://github.com/los93sol/gecko-home-assistant

I'm thinking of just pulling that one and trying it out.

**Comment by los93sol** [comment]
> > @mikeboiko There's changes in geckolib as well that you need for it to work. There's another PR on that repo as well
> 
> Oh gotcha. Does your repo have all the latest changes?
> https://github.com/los93sol/gecko-home-assistant
> 
> I'm thinking of just pulling that one and trying 

> > @mikeboiko There's changes in geckolib as well that you need for it to work. There's another PR on that repo as well
> 
> Oh gotcha. Does your repo have all the latest changes?
> https://github.com/los93sol/gecko-home-assistant
> 
> I'm thinking of just pulling that one and trying it out.

Yes and no.  My repo for gecko-home-assistant has all the home assistant integration changes, and my repo for geckolib has all the lib changes, but not being a python dev I don’t know how to publish the lib so you’ve got to overwrite it currently and at least with my setup on a pi 4 it’s a pain because you end up SSH’ing to your HA machine, then doing a login command and finding the docker container running HA so you can do a docker exec to use vi to replace the lib files with the updates.  I’m sure there’s a smoother workflow for developers, but this is a whole new world for me lol

**Comment by mikeboiko** [comment]
> > > @mikeboiko There's changes in geckolib as well that you need for it to work. There's another PR on that repo as well
> > 
> > 
> > Oh gotcha. Does your repo have all the latest changes?
> > https://github.com/los93sol/gecko-home-assistant
> > I'm thinking of just pulling that one and trying
> 
> > > @mikeboiko There's changes in geckolib as well that you need for it to work. There's another PR on that repo as well
> > 
> > 
> > Oh gotcha. Does your repo have all the latest changes?
> > https://github.com/los93sol/gecko-home-assistant
> > I'm thinking of just pulling that one and trying it out.
> 
> Yes and no. My repo for gecko-home-assistant has all the home assistant integration changes, and my repo for geckolib has all the lib changes, but not being a python dev I don’t know how to publish the lib so you’ve got to overwrite it currently and at least with my setup on a pi 4 it’s a pain because you end up SSH’ing to your HA machine, then doing a login command and finding the docker container running HA so you can do a docker exec to use vi to replace the lib files with the updates. I’m sure there’s a smoother workflow for developers, but this is a whole new world for me lol

I see. I think I will just wait for @gazoodle to test/merge the PRs and I'll try the code after that.

**Pull request merged**
