### PR TITLE
Added version field to manifest.json

### PR DESCRIPTION
**Pull request by brewston**

### CODE REVIEW

**Comment by gazoodle** [comment]
Can you change the version to 0.0.5 please as that's the version number that is current in the github releases then I'll merge the pull. Thanks

**Comment by brewston** [comment]
ok, done

**Comment by gazoodle** [comment]
Thanks @brewston

**Comment by brewston** [comment]
@gazoodle No worries - how does this now find its way into a HACs update ?

**Comment by gazoodle** [comment]
> @gazoodle No worries - how does this now find its way into a HACs update ?

I'm not sure. It might be that the change of version number will be sufficient - I had noticed that previously it gave the version as a 32bit hex number, so perhaps this will be sufficient.

I need to take some time to find out how to control the update mechanism. Perhaps I have to release a new version (and obviously update the version number in the manifest :-) ).

This is my first custom component so I'm learning at the same time!

**Pull request merged**
