### PR TITLE
Fix deprectated constant warnings

### PR DESCRIPTION
**Pull request by xela1**
This should resolve the errors about the deprecated constants #96

### CODE REVIEW

**Comment by jasondefuria** [comment]
Looks good to me!

**Comment by BenJewell** [comment]
Does anyone else have access to approve this besides the repo owner? Not sure if they're still around.

**Comment by xela1** [comment]
He is around, he commented on one of the other repos, but is very busy, he has said he'll be able to dedicate some time to it soon

**Comment by BenJewell** [comment]
Great! Thanks

**Pull request merged**
